Catch AMREX_SPACEDIM static assert errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -117,11 +117,21 @@ jobs:
           ccache -z
           # Extract all EBASE options from GNUmakefile, ignoring comments
           EBASE_OPTIONS=$(grep -oP 'EBASE\s*=\s*\K[^ ]+' GNUmakefile | grep -v '^##')
+
           for TYPE in $EBASE_OPTIONS; do \
             printf "\n-------- ${TYPE} --------\n";
-            make -j ${{env.NPROCS}} EBASE=${TYPE} USE_CCACHE=TRUE ${{matrix.amrex_build_args}}; \
+            OUTPUT=$(make -j ${{ env.NPROCS }} EBASE=${TYPE} USE_CCACHE=TRUE ${{ matrix.amrex_build_args }} 2>&1); \
+            RESULT=$?; \
+            echo "${OUTPUT}"; \
             make realclean; \
-            if [ $? -ne 0 ]; then exit 1; fi; \
+            if [ ${RESULT} -ne 0 ]; then \
+              if echo "${OUTPUT}" | grep -q "static_assert.*AMREX_SPACEDIM\s=="; then \
+                echo "Skipping failure due to AMREX_SPACEDIM assertion for ${TYPE}."; \
+              else \
+                echo "Compilation failed for ${TYPE}. Exiting."; \
+                exit 1; \
+              fi; \
+            fi; \
           done
       - name: Src ccache report
         working-directory: ${{env.BASE_WORKING_DIRECTORY}}
